### E-commerce Dataset Initial Exploration

In [29]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Loading the dataset
df = pd.read_csv('../data/raw/E-commerce_data.csv', encoding='ISO-8859-1')
print("Libraries loaded")

Libraries loaded

In [30]:
# 2. Inspecting the dataset
print("Dataset Shape:", df.shape)

Dataset Shape: (541909, 8)

In [31]:
# 3. Viewing data types and misssing values
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  str
 1   StockCode    541909 non-null  str
 2   Description  540455 non-null  str
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  str
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  str
dtypes: float64(2), int64(1), str(5)
memory usage: 66.2 MB

In [32]:
# 4. Viewing the first 5 rows of the dataset
df.head(5)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/10 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/10 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/10 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/10 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/10 8:26,3.39,17850.0,United Kingdom

In [33]:
# 5. Checking for duplicates
df.duplicated().sum()

np.int64(5268)

In [34]:
# 6. Check for missing values across columns
print("Missing values per column:")
print(df.isnull().sum())

Missing values per column:
InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [35]:
# 7. Viewing the summary statistics for the Quantity and UnitPrice columns
df[['Quantity', 'UnitPrice']].describe()

            Quantity      UnitPrice
count  541909.000000  541909.000000
mean        9.552250       4.611114
std       218.081158      96.759853
min    -80995.000000  -11062.060000
25%         1.000000       1.250000
50%         3.000000       2.080000
75%        10.000000       4.130000
max     80995.000000   38970.000000

#### Initial Data Quality Check

- Missing Values: `CustomerID` has 135,080 missing values, and `Description` has 1,454 missing values.
- Data Types: `InvoiceDate` is stored as text and needs to be converted to datetime. `CustomerID` is stored as `float64` because of the missing values.
- Data Issues: Need to check for negative quantities and zero or negative prices.